tugas1/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib import admin
import tugas_update_status.urls as tugas_update_status
import tugas_halaman_profile.urls as tugas_halaman_profile
import tugas_add_friend.urls as tugas_add_friend
import tugas_stats.urls as tugas_stats

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tugas-update-status/', include(tugas_update_status,namespace='tugas-update-status')),
    url(r'^tugas-halaman-profile/', include(tugas_halaman_profile,namespace='tugas-halaman-profile')),
    url(r'^tugas-add-friend/', include(tugas_add_friend, namespace='tugas-add-friend')),
     url(r'^tugas-stats/', include(tugas_stats, namespace='tugas-stats')),
    url(r'^$', RedirectView.as_view(permanent = True, url = '/tugas-update-status/'), name='index')
]

tugas_add_friend/urls.py
from django.conf.urls import url
from .views import index, message_post,delete_friend
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^message_post', message_post, name='message_post'),
    #url(r'^delete_friend', delete_friend, name='delete_friend')
    url(r'^delete_friend/(?P<id_friend>\d+)/$', delete_friend, name = 'delete_friend'),
    #url(r"^delete_friend", delete_friend, name="delete_friend"),


]

tugas_halaman_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

tugas_stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

tugas_update_status/urls.py
from django.conf.urls import url
from .views import index, add_status, delete_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id_status>\d+)/$', delete_status, name = 'delete_status'),
    ]

tugas_add_friend/models.py
from django.db import models

class Message(models.Model):
    name = models.CharField(max_length=27)
    link = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)

tugas_halaman_profile/models.py
from django.db import models

# Create your models here.

class UserProfile(models.Model):
    name = models.CharField(max_length=250, default="Kak Pewe")
    position = models.CharField(max_length=250, default="Teaching Assistant at University of Indonesia")
    birthday = models.DateField()
    gender = models.CharField(max_length=10, default="Male")
    expertise = models.CharField(max_length=250)
    description = models.TextField()
    email = models.EmailField()
    link = models.TextField(default="https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png")

tugas_stats/models.py
from django.db import models

# Create your models here.

tugas_update_status/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

tugas_add_friend/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan link',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    link = forms.URLField(required=True, widget=forms.URLInput(attrs=attrs))

tugas_update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'What\'s on your mind?'
    }

    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

tugas_add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.test import Client
from django.urls import resolve
from .forms import Message_Form
from .models import Message
from urllib.request import urlopen
import urllib.error

# Create your views here.
response = {'author' : 'Samuel'}
def index(request):
    moedel = Message.objects.all()
    response['form'] = Message_Form
    response['model'] = moedel
    response['title'] = 'Add Friend'
    html = 'addfriend.html'
    return render(request, html, response)

def message_post(request):
    form = Message_Form(request.POST or None)
    moedel = Message.objects.all()
    if(request.method == 'POST' and form.is_valid()):
        if (cek_link(request.POST['link']) == True):
            response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
            response['link'] = request.POST['link']
            moedel = Message(name=response['name'], link=response['link'])
            moedel.save()
            response['status'] = "Done"
            return HttpResponseRedirect('/tugas-add-friend/')
        else:
            response['status'] = "Fail"
            return HttpResponseRedirect('/tugas-add-friend/')
    else:
        response['status'] = "Fail"
        return HttpResponseRedirect('/tugas-add-friend/')

def delete_friend(request, id_friend):
    friend = Message.objects.get(pk = id_friend)
    friend.delete()
    return HttpResponseRedirect('/tugas-add-friend/')

def cek_link(url):
    if ("herokuapp" in url):
        try:
            html = urlopen(url)
            return True
        except urllib.error.HTTPError as err:
            return False
    else:
        return False

tugas_halaman_profile/views.py
from django.shortcuts import render
from .models import UserProfile
# Create your views here.


def index(request):
    profile_tampilan = UserProfile(name="Kak Pewe", position="Teaching Assistant at University of Indonesia",birthday="1998-05-12",
                                   expertise="", description="", email="", gender="Male",
                                   link="https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png")
    profile_tampilan.save()
    profile = UserProfile.objects.get(pk=1)
    splitexp = profile.expertise.split(',')
    response= {'title':'Profile', 'profile': profile, 'splitexp':splitexp}
    return render(request, 'profile.html', response)

tugas_stats/views.py
from django.shortcuts import render
from tugas_halaman_profile.views import UserProfile
from tugas_update_status.models import Status
from tugas_add_friend.models import Message
# Create your views hereself.
response = {}
def index(request):
    profile_tampilan = UserProfile(name="Kak Pewe", position="Teaching Assistant at University of Indonesia",
                                   birthday="1998-05-12", expertise="", description="", email="", gender="Male", 
                                   link="https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png")
    profile_tampilan.save()
    profile = UserProfile.objects.get(pk=1)
    response= {'title':'Stats', 'profile': profile,'friends':len(Message.objects.all()),'feeds':len(Status.objects.all())}
    response['latest'] = Status.objects.last()
    return render(request, 'stats.html', response)

tugas_update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

# Create your views here.
response = {}
def index(request):
    response['author'] = "NHR" #TODO Implement yourname
    status = Status.objects.all()
    response['form'] = Status_Form
    response['model'] = status
    response['title'] = 'Update Status'
    html = 'tugas_update_status.html'
    response['status_form'] = Status_Form
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        #html ='lab_4/form_result.html'
        return HttpResponseRedirect('/tugas-update-status/')
    else:
        return HttpResponseRedirect('/tugas-update-status/')

def delete_status(request, id_status):
    status = Status.objects.get(pk = id_status)
    status.delete()
    return HttpResponseRedirect('/tugas-update-status/')

templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- bootstrap csss -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="icon" href="http://vignette3.wikia.nocookie.net/the-most-popular-girls-in-school/images/1/1a/Linkedin.png/revision/latest?cb=20150730204727">
    <title>
        {% block title %} {{title}} {% endblock %}
    </title>
</head>


<style>
   footer p{
    position: absolute;
    right: 0;
    bottom: 0;
    left: 0;
    padding: 10px;
    text-align: center;
    margin-bottom: 0;
  }

  body{
      font-family: 'Montserrat';
      background-image: linear-gradient(to right, #accbee, #e7f0fd);
  }

  tr, td{
      text-align: left;
      padding: 10px;
  }

  .fotonama{
    display:flex;
    margin-top: 20px;
  }

  #nama{
    justify-content: center;
    align-self: center;
    padding-left: 30px;
    font-size: 50px;
  }

  .friendsfeed{
      display: flex;
      margin-top: 30px;
  }

.tablefeeds{
    font-size: 30px;
}

.subject{
    font-weight: bold;
}

.expert{
    border: 2px solid white;
    padding: 5px;
    padding-left: 10px;
    padding-right: 10px;
    border-radius: 10px;
    margin-right: 10px;
}

</style>

<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>


    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<footer>
  {% block footer %}
  {% include 'partials/footer.html' %}
  {% endblock %}
</body>

</html>

templates/partials/footer.html
<!-- partials/header.html -->
<nav class="navbar navbar-default navbar-fixed-bottom">
  <p>Made with love by Nadyah, Samuel, Prima</p>
</nav>

templates/partials/header.html
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/tugas-update-status/"><img style="max-width:150px; margin-top: -7px;" src="https://image.ibb.co/hy6J6G/lingin_01.png"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav" style="float:right">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="/tugas-update-status/">Status</a></li>
        <li><a href="/tugas-halaman-profile/">Profile</a> </li>
        <li><a href="/tugas-add-friend/">Friends</a> </li>
        <li><a href="/tugas-stats/">Stats</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

tugas_add_friend/templates/addfriend.html
{% extends "layout/base.html" %}
{% block content %}
<style>
#delete-button{
  border: #5DBCD2 solid 2px;
  text-align: center;
  border-radius: 5px;
  background-color: #5DBCD2;
  color: white;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}

#delete-button:hover{
  border: #5DBCD2 solid 2px;
  text-align: center;
  border-radius: 5px;
  background-color: white;
  color: #5DBCD2;
}
#submit{
  width: 10vw;
  margin-left: inherit;
  margin-top: 10px;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}
#submit:hover{
  background-color: white;
  color: #5DBCD2;
}
.flex{
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: flex-start;
  align-items: flex-start;
  align-content: flex-start;
  margin-bottom: 50px;
}
.flex-item{
  padding: 0 15px;
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: 30%;
  border-radius: 5px;
  background-color: white;
  padding: 15px;
  margin: 15px;
  height: 180px;
  min-width: 250px;
}


.name{
  text-align: center;
}
.link{
  text-align: center;
  padding-top: 15px;
}
.added-date{
  color:grey;
  padding: 10px;
}
.added-date:before{
  content: "";
  display: block;
  padding: 18px;
}
.added-date:after{
  content:"";
  display:block;
  background: #fff;
}

/* The alert message box */
.alert {
    padding: 20px;
    background-color: #f44336; /* Red */
    color: white;
    margin-bottom: 15px;
    text-align: center;
}
.alert.success {background-color: #4CAF50;}
/* The close button */
.closebtn {
    margin-left: 15px;
    color: white;
    font-weight: bold;
    float: right;
    font-size: 22px;
    line-height: 20px;
    cursor: pointer;
    transition: 0.3s;
}

/* When moving the mouse over the close button */
.closebtn:hover {
    color: black;
}
@media only screen and (max-width: 768px) {
  .flex-item{
    flex-basis: 90%;
  }
  #submit{
    margin-left: inherit;
    width: 150px;
  }
}
</style>

<br><br>
<section name="input-list" id="input-list">
    <div class="container">
    	<form id="form" method="POST" action="{% url 'tugas-add-friend:message_post' %}">
            <h2>Add Friend</h2>
            {% csrf_token %}
            {{form}}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
    {% if status == "Fail" %}
    <div class="alert">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
      <strong>Link invalid.</strong> Link yang anda masukan tidak tersedia.  
    </div>
    {% elif status == "Done" %}
    <div class="alert success">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>  
      <strong>Success!</strong> Indicates a successful or positive action.
      </div>
    {% endif %}   
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">List Friend</h2>
        {% if model %}
        	<div class="flex">
            {% for data in model %}
				<div class="flex-item" id="friend">
				  <div class="name">{{data.name}}</div>
				  <div class="link"><a href={{data.link}}>{{data.link}}</a></div>
				  <div class="added-date">Added {{data.created_date}}</div>
                  <div class="delete_friend_button">
                    <a href="/tugas-add-friend/delete_friend/{{ data.id }}">
                        <div id="delete-button" class="delete-button" data-id={{data.id}}}>Delete Friend</div>
                    </a>
                  </div>
				</div>
                {% endfor %}
				</div>

        {% else %}
        	<div class="alert alert-danger text-center">
                <strong>Oops!</strong> Kamu belum mempunyai teman.
            </div>
        {% endif %}
    </div>
</section>
{% endblock %}

tugas_halaman_profile/templates/profile.html
{% extends "layout/base.html" %}
{% block content %}
<style>

#editbutton{
  width: 10vw; 
  display:block; 
  margin:0 auto;
  border: #5DBCD2 solid 2px;
  text-align: center;
  border-radius: 30px;
  background-color: #5DBCD2;
  color: white;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}

#editbutton:hover{
  border: #5DBCD2 solid 2px;
  text-align: center;
  border-radius: 30px;
  background-color: white;
  color: #5DBCD2;
}

#submitbutton{
  width: 10vw
}

#expert{
  transition-duration: 0.5s;
}
#expert:hover{
  background-color: white;
}

@media only screen and (max-width: 768px) {
  .profilecenter{
    padding: 20px;
  }
  .img-circle{
    width: 45%;
  }
  #editbutton{
    width: 150px;
  }
  #submitbutton{
    width: 150px;
  }
  #expert{
    margin:3px;
    display: flex; 
  }

  .biodata{
    margin:15px;
  }
}

</style>
<br><br>

<section name="profile" style="margin-bottom:50px">
    <div class="container">
    	<h2>Profile</h2>
    </div>
    <div class="profilecenter">
        <div>
            <img class="img-circle" style="display:block; margin:auto" src= {{profile.link}} width="15%" height="15%"/>
        <h2 style="text-align:center">{{profile.name}}</h2>
        <p style="text-align:center">{{profile.position}}</p>
        </div>
        <div class="container">
                <!-- Trigger the modal with a button -->
                <button class="btn btn-lg btn-block btn-info" id="editbutton" data-toggle="modal" data-target="#myModal">Edit Profile</button>
                <!-- Modal -->
                <div class="modal fade" id="myModal" role="dialog">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Edit Profile</h4>
                      </div>
                      <div class="modal-body">
                        <form>
                          <div class="form-group row">
                            <label for="name" class="col-sm-2 col-form-label">Name</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" id="name" value="{{profile.name}}">
                            </div>
                          </div>
                          <div class="form-group row">
                            <label for="position" class="col-sm-2 col-form-label">Position</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" id="position" value="{{profile.position}}">
                            </div>
                          </div>
                          <div class="form-group row">
                            <label for="description" class="col-sm-2 col-form-label">Description</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" id="description" value="{{profile.description}}">
                            </div>
                          </div>
                          <div class="form-group row">
                            <label for="birthday" class="col-sm-2 col-form-label">Birthdate</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" id="birthdate" value="{{profile.birthday}}">
                            </div>
                          </div>
                          <div class="form-group row">
                            <label for="gender" class="col-sm-2 col-form-label">Gender</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" id="gender" value="{{profile.gender}}">
                            </div>
                          </div>
                            <div class="form-group row">
                              <label for="email" class="col-sm-2 col-form-label">Email</label>
                              <div class="col-sm-10">
                                <input type="email" class="form-control" id="email" value="{{profile.email}}">
                              </div>
                            </div>
                          <div class="form-group row">
                            <label for="expertise" class="col-sm-2 col-form-label">Expertise</label>
                            <div class="col-sm-10">
                              <input type="expertise" class="form-control" id="expertise" value="{{profile.expertise}}">
                            </div>
                          </div>
                        <div class="form-group row">
                          <label for="photo" class="col-sm-2 col-form-label">Photo Image URL</label>
                          <div class="col-sm-10">
                            <input type="link" class="form-control" id="link" value="{{profile.link}}">
                          </div>
                      </div>
                          <div class="form-group row">
                            <div class="col-sm-10" style="float:right">
                              <button type="submit" class="btn btn-lg btn-block btn-info" id="submitbutton">Save</button>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

    </div>
    <div class="biodata">
        <table align="center" style="text-align: center">
            <tr><td class="subject" >Birthday</td><td class="value" >{{profile.birthday}}</td></tr>
            <tr><td class="subject" >Gender</td><td class="value" >{{profile.gender}}</td></tr>
            <tr><td class="subject" >Expertise</td><td class="value">{% for ii in splitexp %}<span id="expert" class="expert">{{ii}}</span>{% endfor %}</td></tr>
            <tr><td class="subject" >Description</td><td class="value" >{{profile.description}}</td></tr>
            <tr><td class="subject" >Email</td><td class="value" >{{profile.email}}</td></tr>
        </table>
    </div>
</section>


<br><br>

{% endblock %}

tugas_stats/templates/stats.html
{% extends "layout/base.html" %}
{% block content %}
<style>
.latest{
  border: 2px solid grey;
  background-color: white;
  border-radius: 5px;
  width: auto;
  padding-top: 20px;
  padding-left: 20px;
  padding-right: 20px;
  padding-bottom: 25px;
  margin-bottom: 10px;
}
.date-added{
  color: grey;
}
.latest .postee{
  margin-bottom: 10px;
  margin-top: -10px;
}
#depe{
  margin: 15px;
}


#kontener{
    padding-left:10%;
}

#nama{
    margin-left:-30%;
}

</style>
<br><br>
<section name="stats" style="margin-bottom:50px">
    <div class="container" id="judul">
    	<h2>Statistic</h2>
    </div>
    <div id="kontener" class="container">
        <div class="fotonama">
            <div class="fotostats">
            <img id="fotostat" class="foto" src= {{profile.link}} style= "width: 40%" "height: 40%">
            </div>
            <h1 id="nama" > {{profile.name}} </h1>
        </div>
        <hr>
        <div class="friendsfeed">
            <table class="tablefeeds">
                <tr >
                    <td class="subject">Friends</td>
                    <td class="value" style="color:grey">{{friends}}</td>
                </tr>
            </table>
            <table class="tablefeeds">
                    <tr>
                        <td class="subject">Feeds</td>
                        <td class="value" style="color:grey">{{feeds}}</td>
                    </tr>
            </table>
          </div>
              <h2 style="padding-left:10px">Latest Post</h2>
              {% if latest %}
        <div id="latest" class="latest">
            <div class="postee">
            <img id="depe" class="img" src= {{profile.link}} width="50px">
            Kak Pewe
            </div>
  				  <div class="isi-status">{{latest.description}}</div>
  				  <div class="date-added" id="date-added">
              {{latest.created_date}}
            </div>
        </div>
        {% else %}
        	<div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada post di timeline.
            </div>
        {% endif %}
    </div>
</section>

<br><br>
{% endblock %}

tugas_update_status/templates/tugas_update_status.html
{% extends "layout/base.html" %}
{% block content %}

<style>
#my-list .container .flex{
  display: flex;
  flex-direction: column-reverse;
  flex-wrap: nowrap;
  justify-content: flex-start;
  align-items: flex-start;
  align-content: flex-start;
  margin-bottom: 50px;
}

#my-list .container .flex #status{
  flex-basis: auto;
  flex-grow: 0;
  flex-shrink: 0;
  border: 2px solid grey;
  background-color: white;
  border-radius: 5px;
  width: 78vw;
  padding-top: 20px;
  padding-left: 20px;
  padding-right: 20px;
  padding-bottom: 25px;
  margin-bottom: 10px;
}

#date-added{
  margin-top: 10px;
  color: grey;
}
#post-button{
  width: 150px;
  margin-right: inherit;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}
#post-button:hover{
  background-color: white;
  color: #5DBCD2;
}
#input-list .container #form .status-form-textarea{
  width: 78vw;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
  border-radius: 5px;
  padding: 10px;
}
#input-list{
  margin-top: 50px;
}
#depe{
  margin: 15px;
  margin-top: -25px;
}
#delete-button{
  width: 20px;
  height: 20px;
  border-radius: 100%;
  padding: 0px;
  margin-left: 73vw;
  background-color: red;
  border-color: red;
  color:white;
  text-decoration: none;
  font-weight: bolder;
  padding-left: 6px;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}
#delete-button:hover{
  background-color: white;
  color: red;
  text-decoration: none;
}
@media only screen and (max-width: 768px) {
  #input-list .container #form .status-form-textarea{
    width: 90vw;
  }
  #post-button{
    width: 150px;
    margin-right: inherit;
  }
  #my-list .container .flex #status{
    width: 90vw;
  }
}
</style>
<br><br>
<section name="input-list" id="input-list">
    <div class="container">
    	<form id="form" method="POST" action="{% url 'tugas-update-status:add_status' %}">
            <h2>Update Status</h2>
            {% csrf_token %}
            {{form}}
            <input id="post-button" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">Timeline</h2>
        <div class="flex">
        {% if model %}
        	{% for data in model %}
          <div class="flex-item" id="status">
            <a href="/tugas-update-status/delete_status/{{ data.id }}">
          <div id="delete-button" class="delete-button" data-id={{data.id}}}>x</div>
        </a>
          <div class="postee">
          <img id="depe" class="img" src = "https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png" width="50px">
          Kak Pewe
        </div>
				  <div class="isi-status">{{data.description}}</div>
				  <div class="date-added" id="date-added">
            {{data.created_date}}
          </div>
        </div>
        	{% endfor %}
        {% else %}
        	<div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada post di timeline.
            </div>
        {% endif %}
      </div>
    </div>
</section>
{% endblock %}